it('should request via axios', async ({ $, t }) => {
  var request = { url: 'http://localhost:9000/test' }

  var result = await $.http('http://localhost:9000')
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 404)
  t.equal(result.statusText, 'Not Found')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.equal(result.data, '')
  t.equal(result.error, 'AxiosError: Request failed with status code 404')

  result = await $.http(request.url)
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, { method: 'GET' })
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'get' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, { method: 'GET' })
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'post' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, { method: 'POST' })
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'put' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, { method: 'PUT' })
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'patch' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, { method: 'PATCH' })
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'delete' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, { method: 'DELETE' })
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'options' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 204)
  t.equal(result.statusText, 'No Content')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, '')
  t.equal(result.error, null)

  result = await $.http({ ...request, method: 'head' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.deepStrictEqual(result.data, '')
  t.equal(result.error, null)
})

it('should request via socks5', async ({ $, t }) => {
  var result = await $.http({ url: 'https://api.ipify.org' })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(typeof result.config, 'object')
  t.equal(typeof result.request, 'object')
  t.equal(typeof result.data, 'string')
  t.equal(result.error, null)
  var axiosIp = result.data

  result = await $.http({ url: 'https://api.ipify.org', socks5: true })
  t.equal(Object.keys(result).length, 7)
  t.equal(result.status, 200)
  t.equal(result.statusText, 'OK')
  t.equal(typeof result.headers, 'object')
  t.equal(result.config, undefined)
  t.equal(typeof result.request, 'object')
  t.equal(typeof result.data, 'string')
  t.equal(result.error, null)
  var socks5Ip = result.data

  t.notEqual(axiosIp, socks5Ip)
})
